### ISSUE TITLE
Review flash and psram

### ISSUE THREAD

**Issue by rodneyosodo** [nakujaproject/N2-onboardTelemetryComputer#12]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

## Context
Review the flash and psramcircuit if it works

## What is the motivation/use case for changing the behaviour?
Store data

**Comment by rodneyosodo** [comment]
Review files can be found [here](https://github.com/nakujaproject/N2-onboardTelemetryComputer/pull/3/files)

**Comment by SammyOina** [comment]
Done, looks good
