### ISSUE TITLE
Specific directories for each component inside the datasheet directory.

### ISSUE THREAD

**Issue by kimanimichael** [nakujaproject/N2-onboardTelemetryComputer#14]
* **I'm submitting a ...**
  - [ ] feature request

Add specific directories to the datasheets directory. Currently, it's difficult to tell which datasheet belongs to which component.

**Comment by rodneyosodo** [comment]
The filename indicates which type of datasheet you are looking at

**Comment by kimanimichael** [comment]
![Screenshot from 2022-04-05 22-37-41](https://user-images.githubusercontent.com/49106674/161835979-0ab20fa1-0de5-4f7a-a935-3e5bcc0e1c71.png)

How exactly? From here it's tedious to tell which datasheet belongs to the USB connector. Or to tell all these datasheets apart from one another.

**Comment by rodneyosodo** [comment]
Are you suggesting I add directories for each file?

**Comment by kimanimichael** [comment]
Yes. Otherwise one has to open almost every datasheet to find a specific one which kind of beats the point of having a datasheets directory.

**Comment by rodneyosodo** [comment]
Done by https://github.com/nakujaproject/N2-onboardTelemetryComputer/commit/c50bcdbef7327d185672606a2ad6f20b47b54328

**Comment by kimanimichael** [comment]
Cool.
