### ISSUE TITLE
Review WIFI amplifier

### ISSUE THREAD

**Issue by rodneyosodo** [nakujaproject/N2-onboardTelemetryComputer#4]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

## Context
Check whether the current implementation of the wifi amplifier with the filter is okay.
A simulation would be great

## What is the motivation/use case for changing the behaviour?
To increase the range of transmission

**Comment by rodneyosodo** [comment]
Review files can be found [here](https://github.com/nakujaproject/N2-onboardTelemetryComputer/pull/3/files)

**Comment by rodneyosodo** [comment]
@ianmuchyri Kindly duplicate the same issue over at https://github.com/nakujaproject/internship2022/issues

**Comment by ianmuchyri** [comment]
The WiFi amplifier circuit looks okay.
