### ISSUE TITLE
Review I2C lines for Flight control and Avionics

### ISSUE THREAD

**Issue by rodneyosodo** [nakujaproject/N2-onboardTelemetryComputer#6]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

## Context
Review the I2C lines if they are correctly placed
- Do we need pull up or pull-down resistors?

## What is the motivation/use case for changing the behaviour?
To be able to receive data from avionics and flight control

**Comment by rodneyosodo** [comment]
Review files can be found [here](https://github.com/nakujaproject/N2-onboardTelemetryComputer/pull/3/files)

**Comment by rodneyosodo** [comment]
@cmucheru and @Simbona  Kindly duplicate the same issue over at https://github.com/nakujaproject/internship2022/issues

**Comment by Simbona** [comment]
confirmed that I2C lines were done properly. The pinouts between the master and slave devices (SDA, SCL) are done correctly.
Complimentary circuit implementation (i.e. pull-ups and VDD/VDD_IO chaining) done as per data sheet recommendations.
@0x6f736f646f
