### ISSUE TITLE
Review reverse voltage protection circuit

### ISSUE THREAD

**Issue by rodneyosodo** [nakujaproject/N2-onboardTelemetryComputer#8]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

## Context
Review the reverse voltage protection circuit if it works
A simulation on proteus or multisim will be great

## What is the motivation/use case for changing the behaviour?
Protect against reverse polarity

**Comment by cmucheru** [comment]
Thankyou for the information. I will review it and give the feedback.

**Comment by rodneyosodo** [comment]
@cmucheru Kindly duplicate the same issue over at https://github.com/nakujaproject/internship2022/issues

**Comment by cmucheru** [comment]
Reviewed the circuit & found it to be working.
@0x6f736f646f
