### ISSUE TITLE
Review voltage regulator circuit

### ISSUE THREAD

**Issue by rodneyosodo** [nakujaproject/N2-onboardTelemetryComputer#9]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

## Context
Review the voltage regulator circuit if it works
A simulation on proteus or multisim will be great

## What is the motivation/use case for changing the behaviour?
Reduce 5V to 3.3V

**Comment by rodneyosodo** [comment]
@cmucheru and @Simbona Kindly duplicate the same issue over at https://github.com/nakujaproject/internship2022/issues

**Comment by cmucheru** [comment]
The circuit is working in Proteus.
Observations:
- Some manuals recommended 10uF output capacitor for current stability.
@0x6f736f646f

**Comment by rodneyosodo** [comment]
Yes. I saw the 10uF recommendation.

**Comment by rodneyosodo** [comment]
@cmucheru add this issue in the interns repo
